import Head from "next/head";
import { Grid, Main } from "../styles/styledHome";
import { getAllProducts } from "./../utils/Service";
import Products from "../components/Products";

export default function Home( {Fruits} ) {
  
  return (
    <div >
      <Head>
        <title>Fruit Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Grid>
        {
          Fruits.map((fruit)=>{
            return <Products key={fruit.id} {...fruit} />
          })
          
        }
        </Grid>
      </Main>
    </div>
  );
}


export async function getServerSideProps(context)  {
  const {data} = await getAllProducts()
  
  return {
      props: {
          Fruits: data
      },
    }
}